apiVersion: v1
kind: Service
metadata:
  labels:
    app: riskident
  name: riskident-svc
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: riskident
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

